### ISSUE TITLE
Merge two groups

### ISSUE THREAD

**Issue by JeremybellEU** [devhub-tud/devhub#151]
Currently merging two groupe due to students creating an incorrect group is a long and tedious task. Moreover it can only be done if you have database access. Therefore it would be nice if course admins can merge groups.

**Comment by JWGmeligMeyling** [comment]
Moving group members in the database is not a problem. Preventing them from accidentally accessing otherones repository for a while is why we only do this by hand, which currently requires a git server restart (which will be fixed in the git server). Students that are enrolled in multiple groups abused a bug that is now fixed. Therefore, this will be a wont have.
