### ISSUE TITLE
Teaching Assistant's comment showing up in the wrong commit version

### ISSUE THREAD

**Issue by awzang** [devhub-tud/devhub#202]
I am following the course "Software Quality and Testing" and I noticed that a comment of a TA is showing up in the wrong commit version, which made me think that the TA was wrong. But it was kind of obvious that she was commenting on the newest version instead of the commit where the comment showed up.

**Comment by JWGmeligMeyling** [comment]
Can you attach an image? Either here or per mail: j.gmeligmeyling@student.tudelft.nl

**Comment by awzang** [comment]
Comment of TA obviously makes no sense here:

![selection_001](https://cloud.githubusercontent.com/assets/7579804/7898396/ee3ebbda-06fe-11e5-89da-8740b531fead.png)

But here it does make sense. This was the tagged commit that was submitted for the assignment.

![selection_002](https://cloud.githubusercontent.com/assets/7579804/7898401/040b7764-06ff-11e5-94ef-cebed087cd37.png)

**Comment by JWGmeligMeyling** [comment]
First of all: that the comment doesn't appear in the file is a problem that will be resolved in the release on monday evening. The comment should be shown in the file.

The reason that the comment appears wrongly in the diff is causes by two things:
* A comment on a line in a file is stored in the line at which it was introduced, because this makes it easier for you to find it back in the commit overview, rather than having to click through the files.
* This comment is wrongly attached to a line that has nothing to do with the comment itself.

Please let me know if, after the new deployment (which will be announced), you still think that this implementation should be changed. For know I just consider this an unlucky placed comment :wink: 

Thanks for the report!

**Comment by awzang** [comment]
You are really into this. I really appreciate your effort. Might spend some time during the summer holiday trying fix small issues for DevHub ;)

**Comment by JWGmeligMeyling** [comment]
If you're interested in this feel free to contact me per mail by this time or at the labwork sessions. I have just deployed the new devhub. The changes will be announced soon :wink:
